# Generated by Django 6.0.3 on 2026-04-16 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_amharic', models.CharField(max_length=200, verbose_name='Name (Amharic)')),
                ('description', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_amharic', models.TextField(blank=True, verbose_name='Description (Amharic)')),
                ('visual_guide', models.ImageField(blank=True, null=True, upload_to='games/visual_guides/', verbose_name='Visual Guide')),
                ('difficulty_level', models.PositiveIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=1, verbose_name='Difficulty Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Name')),
                ('language', models.CharField(choices=[('en', 'English'), ('am', 'Amharic')], default='en', max_length=2, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_amharic', models.CharField(max_length=200, verbose_name='Title (Amharic)')),
                ('content', models.TextField(verbose_name='Content (English)')),
                ('content_amharic', models.TextField(verbose_name='Content (Amharic)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Is Premium')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='core.game', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Game Strategy',
                'verbose_name_plural': 'Game Strategies',
                'ordering': ['order', 'title'],
            },
        ),
    ]
